{{- range .Values.appConfig.genAI.llmProviders.models.azure }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-%s" $.Release.Name .name | lower | quote }}
data:
  apiKey: {{ .api_key | b64enc }}
type: Opaque
---
{{- end }}

{{- range .Values.appConfig.genAI.llmProviders.models.bedrock }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-%s" $.Release.Name .name | lower | quote }}
data:
  aws_secret_access_key: {{ .aws_secret_access_key | b64enc }}
  aws_access_key_id: {{ .aws_access_key_id | b64enc }}
type: Opaque
---
{{- end }}

{{- range .Values.appConfig.genAI.llmProviders.models.openai }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret-%s" $.Release.Name .name | lower | quote }}
data:
  apiKey: {{ .api_key | b64enc }}
type: Opaque
---
{{- end }}

