apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-enrichment
type: Opaque
data:
  dbConnectionString: {{ printf "Host=%s;Port=%d;Username=%s;Password=%s;Database=%s;SearchPath=%s;" .Values.appConfig.db.host (int .Values.appConfig.db.port) .Values.appConfig.db.user .Values.appConfig.db.password .Values.appConfig.db.database .Values.appConfig.db.schema | b64enc }}
  openAIApiKey: {{ include "enrichment.openAIApiKey" . | b64enc }}
  azureDeploymentId: {{ include "enrichment.azureDeploymentId" . | b64enc }}
  azureResourceName: {{ include "enrichment.azureResourceName" . | b64enc }}
