apiVersion: v1
kind: Service
metadata:
  name: {{ template "enrichment.fullname" . }}
  labels:
    app: {{ template "enrichment.name" . }}
    chart: {{ template "enrichment.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if and .Values.service.nodePort (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "enrichment.name" . }}
    release: {{ .Release.Name }}
