apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enrichment.fullname" . }}-litellm-config
  labels:
    app: {{ template "enrichment.name" . }}-litellm-config
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  config: |
    model_list:
    {{- range .Values.appConfig.genAI.llmProviders.models.openai }}
    - model_name: {{ .name }}
      litellm_params:
        model: openai/{{ .model }}
        api_key: os.environ/OPENAI_API_KEY_{{ .name | upper }}
    {{- end }}
    {{- range .Values.appConfig.genAI.llmProviders.models.azure }}
    - model_name: {{ .name }}
      litellm_params:
        model: azure/{{ .model }}
        api_base: https://{{ .resource_name }}.openai.azure.com
        api_key: os.environ/AZURE_API_KEY_{{ .name | upper }}
        api_version: {{ .api_version | default "2024-10-21" | quote }}
    {{- end }}
    {{- range .Values.appConfig.genAI.llmProviders.models.bedrock }}
    - model_name: {{ .name }}
      litellm_params:
        model: bedrock/{{ .model }}
        aws_region_name: {{ .aws_region_name }}
        aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY_{{ .name | upper }}
        aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID_{{ .name | upper }}
        drop_params: true
    {{- end }}
    litellm_settings:
      num_retries: {{ .Values.appConfig.genAI.openAIRetryOnFailureCount | default 0 }}
      request_timeout: {{ .Values.appConfig.genAI.openAIHttpClientTimeoutSec | default 10 }}
      {{- if and .Values.litellm.fallbacks (ne (len .Values.litellm.fallbacks) 0) }}
      fallbacks: {{ .Values.litellm.fallbacks | toYaml | nindent 8 }}
      {{- end }}
      turn_off_message_logging: {{ .Values.litellm.turn_off_message_logging | default true }}
      {{- if .Values.litellm.success_callback }}
      success_callback: {{ .Values.litellm.success_callback }}
      {{- end }}
      {{- if .Values.litellm.failure_callback }}
      failure_callback: {{ .Values.litellm.failure_callback }}
      {{- end }}
      {{- if .Values.litellm.callbacks }}
      callbacks: {{ .Values.litellm.callbacks | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.litellm.debug }}
      debug: {{ .Values.litellm.debug }}
      {{- end }}
      {{- if .Values.litellm.verbose }}
      verbose: {{ .Values.litellm.verbose }}
      {{- end }}
    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
