model_list:
  - model_name: openai-gpt-4o
    litellm_params:
      model: os.environ/OPENAI_MODEL
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-text-embedding-3-large
    litellm_params:
      model: os.environ/OPENAI_EMBEDDING_MODEL
      api_key: os.environ/OPENAI_API_KEY_TEXT_EMBEDDING
  - model_name: azure-gpt-4o-latest
    litellm_params:
      model: os.environ/AZURE_MODEL
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2024-10-21"
  - model_name: azure-text-embedding-3-large
    litellm_params:
      model: os.environ/AZURE_EMBEDDING_MODEL
      api_base: os.environ/AZURE_EMBEDDING_API_BASE
      api_key: os.environ/AZURE_API_TEXT_EMBEDDING
      api_version: "2024-10-21"
general_settings:
  master_key: os.environ/PROXY_MASTER_KEY